### PR TITLE
Added option in addTiledImage to replace tiledImage at index.

### PR DESCRIPTION
**Pull request by LarissaSmith**
Based on the discussion of https://github.com/openseadragon/openseadragon/pull/701, I changed my pull request to a replace tiledImage API. Added the API as an option on addTiledImage.

### CODE REVIEW

**Comment by iangilman** [comment]
Looks good. My only concern is race conditions...it's possible for the world list to have changed between the time addTiledImage is called and the time the image actually loads. On the other hand, we already have that issue even without the `replace` flag, so this doesn't make things any worse. @LarissaSmith what do you think? 

Also, would you be up for adding a test for this new feature?

**Comment by LarissaSmith** [comment]
Hmm... At the beginning of the function, I could get the world item that should be removed and use it to make sure the right item is replaced. That way there won't be a disadvantage from using the index parameter instead of passing in the item.

Sure, I'll get started on a test.

**Comment by LarissaSmith** [comment]
I fixed the race condition and added a test for this.

**Comment by iangilman** [comment]
Lovely! Thank you for making this happen :)

**Pull request merged**
