### PR TITLE
fixed dzitilesource guessing of tilesUrl.

### PR DESCRIPTION
**Pull request by gaetano-guerriero**
Now the regex guessing the root url of tiles works also if the data
url (the url from which information about the tile was downloaded) does
not ends with .dzi, .xml or .js.

### CODE REVIEW

**Comment by iangilman** [comment]
@gaetano-guerriero Beautiful! Thank you for adding the test as well. One thing: could you add it to https://github.com/openseadragon/openseadragon/blob/master/test/coverage.html too?

**Comment by iangilman** [comment]
Just noting: fixes #832.

**Comment by gaetano-guerriero** [comment]
@iangilman  done, test module added to coverage run

**Comment by iangilman** [comment]
Beautiful, thank you!

**Pull request merged**
