### PR TITLE
Build and doc update

### PR DESCRIPTION
**Pull request by avandecreme**
See commits messages for details.

### CODE REVIEW

**Comment by iangilman** [comment]
Awesome! Long overdue I suppose. All looks lovely. 

Can you explain the changes with concat and uglify?

**Comment by avandecreme** [comment]
>Can you explain the changes with concat and uglify?

The latest version of concat supports source map, so I added it generation. With netbeans this allows me to debug right from my text editor.

As for uglify, I set it up to reuse the concat source map, so it maps directly to the original (split) source files. This can be disabled to map to openseadragon.js instead as we had before. What do you think?

I also removed all comments from the minified version (except for the banner). I think this makes more sense.

**Comment by iangilman** [comment]
Awesome, that all sounds good; thanks for the explanation.

**Comment by iangilman** [comment]
@avandecreme Hmm...when I do `npm install` it runs the `prepublish` script (which builds). I wasn't expecting that...I figured it would just happen before you published to npm, not while installing dependencies. 

I guess it's not the worst thing; it seemed to complete ok. On the other hand, when I did a clean `npm install` the grunt build happened before a bunch of the grunt packages were even installed (or so it seemed according to the terminal output), which seems odd. 

What do you think?

**Comment by avandecreme** [comment]
> @avandecreme Hmm...when I do npm install it runs the prepublish script (which builds). I wasn't expecting that...I figured it would just happen before you published to npm, not while installing dependencies.

Yes, that is one odd thing with npm:
> prepublish: Run BEFORE the package is published. (Also run on local npm install without any arguments.)

https://docs.npmjs.com/misc/scripts

>I guess it's not the worst thing; it seemed to complete ok. On the other hand, when I did a clean npm install the grunt build happened before a bunch of the grunt packages were even installed (or so it seemed according to the terminal output), which seems odd. 

My output is similar to what we have here: https://travis-ci.org/openseadragon/openseadragon
Lines 110 to 484
I guess this is another npm oddity. It seems to print the tree of packages after the build output even though they were installed before...

**Comment by iangilman** [comment]
Okey dokey...it's probably a good thing all told; just surprising. Thanks for the clarification.

**Pull request merged**
