### PR TITLE
Animate rotation

### PR DESCRIPTION
**Pull request by avandecreme**
This is a first draft.
The issue is that 0 degrees is not the same as 360 anymore:
https://drive.google.com/file/d/0BzAcRIdakTF0Q0VVV1F0eTI1aEk/view?usp=sharing

Are we ok with removing the modulo? I can't think of any issue with it but I am not too confident either.

### CODE REVIEW

**Comment by iangilman** [comment]
Looks great so far! I agree we should just remove the modulo. It's probably better anyway for it to be whatever value the user entered, even if that's greater than 360 or less than 0. 

Seems like this patch could use a test or two?

**Comment by iangilman** [comment]
Just a note: this address is the individual image portion of #1060.

**Comment by iangilman** [comment]
Random thought: I don't know if there's any spot where there's a `rotation === 0` optimization, but if there is, you'll maybe want to extend that to include a modulus at the point of the check.

**Comment by iangilman** [comment]
Noting: fixes #1106

**Comment by avandecreme** [comment]
Done !

**Comment by iangilman** [comment]
Looking good!

**Pull request merged**
