### PR TITLE
Fix JSDoc.

### PR DESCRIPTION
**Pull request by avandecreme**
The doc is broken with the latest version of JSDoc.
It looks like a module can't be a namespace as well. The problem is that I can't find a way to document the window.OpenSeadragon function anymore.

I also fixed an issue with the margins methods which created a bug in the menu (see global at http://openseadragon.github.io/docs/ )

### CODE REVIEW

**Comment by iangilman** [comment]
I guess maybe `window.OpenSeadragon` should just be mentioned in the `Viewer` constructor? 

http://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#Viewer

Of course we also use it in our examples. Between those things that should be enough.

**Comment by avandecreme** [comment]
That seems like a good option. I also had to update the templates files in site-build. I will make a pull request when it is ready.

**Comment by iangilman** [comment]
Cool. Are you going to update this PR with a mention  in the Viewer constructor?

**Comment by avandecreme** [comment]
Yes. I will see what work best once the templates are ready.

**Comment by iangilman** [comment]
Sounds good :)

**Comment by avandecreme** [comment]
Done. Goes with https://github.com/openseadragon/site-build/pull/130

**Comment by avandecreme** [comment]
Preview:
screenshot_20160409_102657

**Comment by iangilman** [comment]
Beautiful!

**Pull request merged**
