### PR TITLE
Better handle destruction when navigator in custom location

### PR DESCRIPTION
**Pull request by woodchuck**
This probably needs more work, but here's a start.

### CODE REVIEW

**Review by iangilman — APPROVED** [review]
Looks good to me! @Woodchuck thank you for making this patch!

@zero41120 @JoFrMueller @msalsbery what do you think? Does this solve the problem for you?

**Comment by woodchuck** [comment]
@iangilman Don't merge this yet. I've found it has a bug with fullscreen. `onFullScreen` calls `this.buttons.emulateExit();` which doesn't work if `this.buttons` is an array vs. a ButtonGroup.

**Comment by woodchuck** [comment]
@iangilman I've addressed the fullscreen problem. I think this is safe to merge now as far as that goes.

**Review by msalsbery — APPROVED** [review]
Looks great, works great!

**Comment by msalsbery** [comment]
@JoFrMueller This patch fixes the issue I found (#1878)...does it fix issues you were having?

**Comment by msalsbery** [comment]
@iangilman  I'm good with merging this...I've got the changes integrated into my big patch as well (git stashed) and all works well there!

@woodchuck  Great first contribution, thank you for doing this!

**Comment by JoFrMueller** [comment]
@msalsbery I don't even had issues as I didn't put the navigator in a custom location so far to be honest. I guess, I just introduced this mess by starting to hunt down memory leaks (and therefore introduced some too optimistic deletion calls) without testing enough valid configurations as it seems...

So if it cleans up correctly now and doesn't throw any errors anymore, I'm very happy that the originally created mess (though introduced with noble goals) is eliminated. Thanks a lot!

**Comment by msalsbery** [comment]
@woodchuck 

One more thing before we land this...can you please add an entry to changelog.txt?

@iangilman Anything else to add here?

**Comment by msalsbery** [comment]
> So if it cleans up correctly now and doesn't throw any errors anymore, I'm very happy that the originally created mess (though introduced with noble goals) is eliminated. Thanks a lot!

@JoFrMueller cool, thank you!

**Comment by msalsbery** [comment]
@iangilman This one is cool to land for 2.5.0 as well if you're cool with it!

**Comment by woodchuck** [comment]
> One more thing before we land this...can you please add an entry to changelog.txt?

@iangilman Done!

**Review by msalsbery — APPROVED** [review]
@woodchuck  Excellent, merging!  Thank you for this!

**Comment by iangilman** [comment]
Wonderful! Thank you for taking care of this, @woodchuck, and thank you for diving on the review/merge @msalsbery!

Unfortunately my schedule these days makes it hard for me to get to OpenSeadragon like I would like to… I'm thankful for everyone pitching in :-)

**Comment by iangilman** [comment]
@arthur-flam Thank you for pointing this out! I'm sorry I didn't notice this breaking change before it was merged! 

It seems like it might be worth providing an alias with the deprecated property... It could be as simple as adding this to the Viewer class: 

```
get buttons() {
  console.warn('Viewer.buttons is deprecated; please use Viewer.buttonGroup');
  return this.buttonGroup;
}
```

Would you be up for making a PR here to this effect? If not, would you mind at least filing a new issue for the breakage? Thanks again!

**Comment by iangilman** [comment]
Okay, I've gone ahead and created an issue: https://github.com/openseadragon/openseadragon/issues/2146

**Pull request merged**
