### PR TITLE
MouseTracker Improvements

### PR DESCRIPTION
**Pull request by msalsbery**
1) Exposed secondary pointer button (middle, right, etc.) events from MouseTracker and through viewer (#479)
2) Improved IE 8 compatibility

### CODE REVIEW

**Comment by iangilman** [comment]
Looks good. Might be worth somehow clarifying that the "aux" handlers are for all non-primary buttons, not just the "aux/middle" button.

**Comment by msalsbery** [comment]
>Might be worth somehow clarifying that the "aux" handlers are for all non-primary buttons, not just the "aux/middle" button.

@iangilman Where? I thought I did that...

**Comment by iangilman** [comment]
Fair enough. I guess I'm thinking that it could be confusing to use the same name in both cases.  On the other hand, it's a rare enough use case maybe we shouldn't worry about it. If it turns out there's confusion, we can make a finer point of it.

**Comment by msalsbery** [comment]
@iangilman Renamed!

**Comment by msalsbery** [comment]
grr last commit not good enough to fix that bug. Fixing...

**Comment by msalsbery** [comment]
Fixed.

**Comment by iangilman** [comment]
Looks good, except the unit test failures.

**Comment by msalsbery** [comment]
Ok, stable again. Now see if I can add a fix... :)

**Comment by msalsbery** [comment]
@iangilman 

Didn't change the pointer events shim! Should be okay now.

**Comment by iangilman** [comment]
Cool; looking good. 

One thought for the future: maybe we could start to consolidate the IE8 special cases (and refactor as needed to make it possible), so that when we're ready to break IE8 support out as a plugin, it's already more or less ready.

**Comment by msalsbery** [comment]
Agreed. I looked at making the plugin starting with MouseTracker and realized how much was sealed/private that I'd have to copy so I put it off pending other fixes, particularly the iframe issue (ugh).

**Pull request merged**
