### PR TITLE
Functionality extension : Image Cropping

### PR DESCRIPTION
**Pull request by matta971**

### CODE REVIEW

**Comment by matta971** [comment]
Adding the native functionality for cropping a partial content of the Viewer.

**Comment by iangilman** [comment]
@matta971 I don't see any code changes in this pull request. Can you try again?

**Comment by matta971** [comment]
I haven't done any changes yet, I created the pull request to inform about
what I want to work on.
By the way, if someone had done this functionality or begun it it could be
interesting.

On Thu, Feb 12, 2015 at 6:09 PM, Ian Gilman <notifications@github.com>
wrote:

> @matta971 <https://github.com/matta971> I don't see any code changes in
> this pull request. Can you try again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openseadragon/openseadragon/pull/598#issuecomment-74110059>
> .
>



-- 
ALCIME Matthieu
http://malcime.alwaysdata.net/portfolio/
http://aliaz.com/matthieu-alcime

**Comment by iangilman** [comment]
Gotcha, cool. No one has done it, but I've recently proposed it with #594. I know there are other people who would love to see it happen!

**Comment by matta971** [comment]
I achieved in a way this functionnality but I have some questions. In order
for that to work, I use an external plugin called imgAreaSelect (
http://odyniec.net/projects/imgareaselect/) using a MIT and a GPL license.
It let me create a cross-browser cropping area.
My first question is : In which way can I include it in the project
(technically speaking) ?
Then I am still thinking about the way to activate the functionnality, do
you that a new button could be enough?

Thank you in advance,

On Fri, Feb 13, 2015 at 6:14 PM, Ian Gilman <notifications@github.com>
wrote:

> Gotcha, cool. No one has done it, but I've recently proposed it with #594
> <https://github.com/openseadragon/openseadragon/issues/594>. I know there
> are other people who would love to see it happen!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openseadragon/openseadragon/pull/598#issuecomment-74289449>
> .
>



-- 
ALCIME Matthieu
http://malcime.alwaysdata.net/portfolio/
http://aliaz.com/matthieu-alcime

**Comment by iangilman** [comment]
I see, you're talking about an interactive cropping UI? That's different from what is proposed in #594, which would be just the cropping code without the UI. Sounds cool, though. 

I think the UI aspect is beyond the scope of the core OpenSeadragon library, but would make a great plug-in. Also, we're not going to incorporate external libraries such as imgAreaSelect in the core project, but that would be fine for a plug-in. 

As for how to engage it, yes, a button seems reasonable.

**Comment by matta971** [comment]
Hello,
I am having trouble doing my cropping functionnality cause I'd like to
forbid my selection square from getting out of the real image area. Thus I
need a function which gives the upper left and the bottom right points
coordinates of this image . Reading the documentation, I have found some
functions which get the bound of the viewport or the viewer container but
not the picture created itself.

Could you tell me if there is such a function or if someone is developping
it?

On Tue, Feb 17, 2015 at 6:10 PM, Ian Gilman <notifications@github.com>
wrote:

> I see, you're talking about an interactive cropping UI? That's different
> from what is proposed in #594
> <https://github.com/openseadragon/openseadragon/issues/594>, which would
> be just the cropping code without the UI. Sounds cool, though.
>
> I think the UI aspect is beyond the scope of the core OpenSeadragon
> library, but would make a great plug-in. Also, we're not going to
> incorporate external libraries such as imgAreaSelect in the core project,
> but that would be fine for a plug-in.
>
> As for how to engage it, yes, a button seems reasonable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openseadragon/openseadragon/pull/598#issuecomment-74706294>
> .
>



-- 
ALCIME Matthieu
http://malcime.alwaysdata.net/portfolio/
http://aliaz.com/matthieu-alcime

**Comment by iangilman** [comment]
Yes, this is more explicit in the unreleased version that's on master right now. In that case, assuming you have only one image in the viewer, it would be something like `viewer.world.getItemAt(0).getBounds()` to get the image bounds in viewport coordinates. 

If you don't want to use this newer version, in earlier versions you just need to calculate the aspect ratio of the image to find out where the bottom edge is. Left is always 0, right is always 1, top is always 0 and bottom is `height / width`.

**Comment by matta971** [comment]
Thank you very much for the answer.
I don't know if you corrected this in the unreleashed version but I have
noticed some problem when i rotate. Indeed, in my application I put
rectangles on specific places upon the picture but when I rotate it's no
longer at the right place. Furthemore I use the imageToViewportCoordinates
function to make some conversions form my mouse position to the viewport
coordinates and the results are no longer satisfying after a rotation.

On Wed, Mar 4, 2015 at 6:30 PM, Ian Gilman <notifications@github.com> wrote:

> Yes, this is more explicit in the unreleased version that's on master
> right now. In that case, assuming you have only one image in the viewer, it
> would be something like viewer.world.getItemAt(0).getBounds() to get the
> image bounds in viewport coordinates.
>
> If you don't want to use this newer version, in earlier versions you just
> need to calculate the aspect ratio of the image to find out where the
> bottom edge is. Left is always 0, right is always 1, top is always 0 and
> bottom is height / width.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openseadragon/openseadragon/pull/598#issuecomment-77204389>
> .
>



-- 
ALCIME Matthieu
http://malcime.alwaysdata.net/portfolio/
http://aliaz.com/matthieu-alcime

**Comment by iangilman** [comment]
@matta971 Good question; I don't know if those issues have been fixed. 

You might also check out #193, #463, and #567.

**Comment by iangilman** [comment]
Closing this PR due to lack of activity. Feel free to reopen if you get back into it, @matta971.

**Pull request closed without merging**
