### PR TITLE
feat(navigator): add option autoFade

### PR DESCRIPTION
**Pull request by leesei**
I would like to control the visibility of navigator minimap in my application, so I added an option to prevent autoFade.

This is my code for toggling:
```js
navigationElement = viewer.navigator.element;
navigationElement.classList.toggle('navigatorHidden');
// OR
navigationElement.style.visibility = 'hidden';
```

```css
.navigatorHidden {
  visibility: hidden;
}
```

### CODE REVIEW

**Comment by leesei** [comment]
Any comments on this feature?
I have yet to add test for this.

**Comment by iangilman** [comment]
Beautiful! Good idea, well implemented. 

I don't know that a test for this feature is necessary, but I'm happy to have one if you want. Let me know either way; otherwise I think it's ready to land.

**Comment by avandecreme** [comment]
Should that line be changed to `options.autoFade` as well?
https://github.com/openseadragon/openseadragon/pull/935/files#diff-1aad0827e27dc50095117096590b4f21L91

Note that it would change the default value to true.

**Comment by leesei** [comment]
@iangilman If you're okay with it I think adding an usage on the example page after this feature has landed is good enough. I can work on that then.

@avandecreme if the user is specifying an id for navigator, that would imply they need total control. So   OSD wouldn't autofade for them. That's the original idea and I'm buying that.
What I did was to let OSD not to autofade the automatically generated navigator.

**Comment by iangilman** [comment]
@avandecreme Good spotting, but yeah, I'm fine with keeping that path manual, and that's how @leesei has set up the docs. 

@leesei I'll go ahead and land. Thank you for the patch!

**Comment by leesei** [comment]
For the example of this feature, do I add HTML to this page directly?
https://github.com/openseadragon/openseadragon.github.com/blob/master/examples/ui-viewport-navigator/index.html

**Comment by iangilman** [comment]
Actually that's just the built version... to make the change you need to modify the file in this other project: 

https://github.com/openseadragon/site-build/blob/master/www/ui-viewport-navigator.html

**Comment by leesei** [comment]
Glad I asked. PR coming in a few days.

**Pull request merged**
