### PR TITLE
Fix zoom out when wheel event.deltaY is zero

### PR DESCRIPTION
**Pull request by cavenel**
Don't apply zoom in or zoom out when deltaY is zero on wheel events. Should fix https://github.com/openseadragon/openseadragon/issues/947 and not make OpenSeadragon zoom out when scrolling horizontally on a touchpad.

### CODE REVIEW

**Review by iangilman — CHANGES_REQUESTED** [review]
@cavenel Wow, thank you for finding this and fixing it!

I see there's a lot of code in here about a `debouncePanEvents` which seems unrelated to the zoom fix. Was that intended for something else? It would be good to keep PRs to one feature at a time.

**Comment by cavenel** [comment]
Oups, sorry I didn't intend to add these in the PR! I'll clean that, I just wanted the small fix here.

**Comment by cavenel** [comment]
Should be good now, I reverted the second commit that introduced these changes.

**Comment by msalsbery** [comment]
Ugh! Artificial scroll events from trackpads...another well known pain point for web events ;)

This fix is good, thanks @cavenel !

**Review by iangilman — APPROVED** [review]
@cavenel Great, thank you for cleaning this up, and for fixing it in the first place!

@msalsbery Thank you for reviewing :)

**Pull request merged**
