### PR TITLE
See #832, further fix for dzitilesource guessing of tilesUrl, for iii…

### PR DESCRIPTION
**Pull request by altert**
for iiipserver configurations like /iiipsrv?DeepZoom=/path/my.dzi.
current configuration, introduced in #835 breaks this config

### CODE REVIEW

**Comment by iangilman** [comment]
@altert Excellent. I see you've posted in #1017 as well. Could you also take a look at #986 to see if  this patch addresses that issue as well?

It looks like this patch might need a little more work, as a related test is failing in the build:

https://travis-ci.org/openseadragon/openseadragon/builds/173829931

One possibility, if we can't find a single regex that works, would be to try a couple in series and if any of them pass, we're good.

**Comment by altert** [comment]
oops typo creeped in the test conditions.

**Comment by iangilman** [comment]
Excellent. Okay, I just want to give this a few more days for people to weigh in.

**Comment by iangilman** [comment]
Okay, we've got confirmation on #986... merging. @altert thank you again for making this fix!

**Pull request merged**
