### PR TITLE
No longer loading too many tiles

### LINKED ISSUE #1020: Loading too many tiles after #1014
After landing #1014 @johnsusi and I have noticed that it's now loading more tiles than it needs. Beforehand (in my experience) it loads the highest level that covers the entire image with a single tile and then progresses upward from there. Now it does that but also progresses downward, loading every single level down to level 0. In @johnsusi's case he had `immediateRender` on, so it's even more dramatic that it's loading everything (instead of just the top level it needed).

Obviously we don't want to be loading these unnecessary tiles. One approach would be to roll back #1014, but I think it's actually the right step forward, and it's just uncovered an existing flaw in our logic, so I propose we leave the patch and seek to fix this new issue.

One theory: When we go through looking for the next tile to load perhaps we don't have a "don't bother" threshold. Now with #1014 we keep looking for next tiles to load more aggressively, so we need to institute that threshold. It should be based on the knowledge that the tiles needed to cover the scene are already in process somehow.

Note that if a high level tile fails to load, we should then fall back to loading a tile below it to cover that space. Perhaps our current code treats "this tile is currently being loaded" as a load failure.

@johnsusi says he'll dig into it, and perhaps @CaptainCodeman can be of help as well.

### PR DESCRIPTION
**Pull request by iangilman**
Tracking tile loading separately from tile drawing for purposes of determining what to load next. Fixes #1020

### CODE REVIEW

**Comment by avandecreme** [comment]
Just tested, works perfectly 👍

**Comment by avandecreme** [comment]
Ha, I think I found a bug actually. Some tiles do not get loaded anymore when they should:
https://drive.google.com/file/d/0BzAcRIdakTF0emp5YnpCVGl3R2s/view?usp=sharing

**Comment by iangilman** [comment]
@avandecreme Wow, thank you for catching that! Looks like we need to be more aggressive about clearing out the old `loadingCoverage` since loading is a more ephemeral state. I think I've fixed it now; please take another look :)

@johnsusi @CaptainCodeman @rdlester Do any of you want to take a look as well?

**Comment by CaptainCodeman** [comment]
Sure, I'll try and test it out today.

**Comment by rdlester** [comment]
It's been a while since I"ve looked at this code, so I don't remember how failure cases are handled, but what happens if an attempted load fails and the image isn't fetched? If you'd like to retry, it seems loadingCoverage should get unset.

**Comment by CaptainCodeman** [comment]
Seems to be working OK for me 👍

**Comment by iangilman** [comment]
@rdlester Good thought! Here's what happens: when a failure is encountered, the tile's `loading` flag is set back to false. The `loadingCoverage` is reset to empty at the beginning of each frame and repopulated with the latest `loading` and `loaded` flags, so it picks up the failure properly. 

@CaptainCodeman Thank you for testing it!

**Comment by avandecreme** [comment]
I haven't found the time to test with the reset in updateViewport, but won't we load too many tiles if the viewport is moving?

**Comment by iangilman** [comment]
@avandecreme The `loading` and `loaded` flags of the individual tiles aren't being reset, so it doesn't cause any additional tiles to load. It's just that `loadingCoverage` is being refreshed every frame to make sure we have the correct latest information based on those flags from the individual tiles. Does that make sense?

**Comment by avandecreme** [comment]
Alright, good for me then.

**Comment by iangilman** [comment]
@avandecreme Great, thank you for looking it over!

I think all that's left is to get to the bottom of the issue @susanmonnelly reported in #1020. Susan, any thoughts after my last response?

**Comment by iangilman** [comment]
Okay, we've got a clean bill of health on this from @susanmonnelly (who had found an issue).

**Pull request merged**
