### PR TITLE
add support for iiif preferredFormats

### LINKED ISSUE #1655: support iiif preferredFormats
I tried to introduce `formatHints` in https://github.com/openseadragon/openseadragon/pull/1625 but the feature wasn't standard then. It now has been renamed as `preferredFormats` and has been accepted (see [this TRC](https://github.com/IIIF/trc/issues/21) and [this merge](https://github.com/IIIF/api/pull/1816)).

I'd like to prepare a pull request to support it in OSD, hence this issue

### PR DESCRIPTION
**Pull request by eroux**
fixes #1655

### CODE REVIEW

**Comment by eroux** [comment]
@azaroth42 does that look reasonable?

**Comment by iangilman** [comment]
Looks good to me from an OSD standpoint. I'm interested in hearing what @azaroth42 thinks from a IIIF standpoint.

@eroux thank you for following up on this!

**Comment by eroux** [comment]
@azaroth42 would you have time to review this?

**Comment by eroux** [comment]
the new beta has the preferredFormat: https://iiif.io/api/image/3.0/#55-preferred-formats

**Comment by iangilman** [comment]
@azaroth42 shall we land this here? Looks like it's on its way in IIIF, so it would be good to have it here in OSD. I just want to make sure you agree.

**Comment by azaroth42** [comment]
Looks good to me :)  Thanks both!

**Comment by iangilman** [comment]
Great, thanks for taking a look, @azaroth42!

...And thank you for making these changes, @eroux!

**Comment by eroux** [comment]
thanks!

**Pull request merged**
