### PR TITLE
Fix viewport margins with rotation. Fix #1007

### LINKED ISSUE #1007: Overlay location on rotated canvas changing on zooming
I have encountered an issue with overlays in an OpenSeadragon canvas with viewportMargins. If the image is rotated (by multiple of 90°) the overlays move in relation to the underlying image when zoomin in or out. 
Below is some sample code

```
<style>
.overlay {
	background-color: red;
	opacity: 0.5;
}

#openseadragon {
	width: 1200px;
	height: 800px;
}
</style>

	<div id="openseadragon"></div>
	<script type="text/javascript">
        var viewer = OpenSeadragon( {
            id: "openseadragon",
            showNavigationControl: false,
            showZoomControl: false,
            showHomeControl: false,
            tileSources: "http://ub-goobi-pr2.ub.uni-greifswald.de/viewer/iiif/image/PPN746612338/00000001.tif/info.json",
            overlays: [ {
                id: 'test-overlay',
                x: 0.43,
                y: 0.38,
                width: 0.23,
                height: 0.12,
                className: 'overlay',
            } ],
            viewportMargins: {
                top: 0,
                left: 0,
                right: 0,
                bottom: 50
            
            }
        } );
        viewer.viewport.setRotation( 90 );
    </script>
```

### PR DESCRIPTION
**Pull request by avandecreme**
The issue in #1007 was actually due to a conversion error with margins + rotation.
I had to do a bigger refactoring than expected: I got rid of containerInnerSize and let getHomeBounds takes margins into account instead.

One side effect is that `getBounds` now includes margins but the previous behavior seems dangerous to me because margins are only relevant when at home.

### CODE REVIEW

**Comment by iangilman** [comment]
@avandecreme Any more thoughts on this based on our conversation in Gitter?

**Comment by avandecreme** [comment]
I just need some time to make it fully backward compatible :)

**Comment by iangilman** [comment]
Cool... no rush, of course :)

**Comment by iangilman** [comment]
@avandecreme don't forget about this patch :)

**Comment by avandecreme** [comment]
I gave some thoughts about it but I'm afraid I don't see how to solve this.
Unfortunately, the content of this PR probably can't be reused to get to a correct fix.

**Comment by iangilman** [comment]
Fair enough. Any more thoughts on #1007? Do you want to post there to let the issue reporter know that we've hit a dead end?

Should we close this PR?

**Comment by avandecreme** [comment]
I posted in #1007. I think we can close this PR because it isn't doing what the viewport margins are supposed to do.

**Comment by iangilman** [comment]
Cool, sounds good. Thanks for taking a stab at it!

**Pull request closed without merging**
