### PR TITLE
Fix flick gesture with rotation. Fix #869

### LINKED ISSUE #869: Can't scroll after a couple of rotations and zooms on iPad
The following issue was encountered during openseadragon usage: at some point scrolling stops workin on iPad (I used iPad Pro). Steps to reproduce are the following:
1. Zoom from default view
2. Rotate image to random angle
3. Move to some point of the image
4. Rotate one more time to random angle
5. Scroll to the top

Expected result:
Scoll works

Actual result:
Image is scroll a bit but then returned back, it looks like something blocks scrolling. 
The issue looks similar to https://github.com/openseadragon/openseadragon/issues/833
Video of the issue is here: http://monosnap.com/file/FUNT0zBSxoVE1NaNb06iY0nA6ilYB4
Please let me know if you need any details

### PR DESCRIPTION
**Pull request by avandecreme**
I wonder what we should do with panHorizontal/panVertical set to false when the viewport is rotated.

### CODE REVIEW

**Comment by avandecreme** [comment]
Ok for now, I just made panHorizontal/panVertical consistent with what happen on desktop.

**Comment by iangilman** [comment]
Looks good... this works because the rotation is now factored into those viewport calls, right?

**Comment by avandecreme** [comment]
Yes!

**Comment by iangilman** [comment]
@avandecreme Do you know if this issue was present in 2.1.0 or introduced since then? I'm wondering what to put in the change log.

**Comment by avandecreme** [comment]
It was introduced by my changes on rotation. I don't think it needs to be in the changelog.

**Comment by iangilman** [comment]
Cool, thanks for confirming, and of course thanks for fixing!

**Pull request merged**
