### PR TITLE
Comments for some private functions in TiledImage.

### PR DESCRIPTION
**Pull request by rdlester**
Adding comments now to help keep track of types before I start modifying the drawing loop. Will expand the comments as I start working with the actual logic.

### CODE REVIEW

**Comment by avandecreme** [comment]
I have been modifying the drawing loop heavily in #1006
So we will have a lot of conflicts.
What would you like to change in there?
I won't have time to pursue #1006 for a while so I can let you take it over if you want to.

**Comment by iangilman** [comment]
@rdlester Exciting! Are you going to be working on these topics?

https://github.com/openseadragon/openseadragon/issues/created_by/rdlester

Sounds like it would be good to coordinate with @avandecreme.

I love these new comments but for one detail: I don't want the private functions documented on our documentation site:

http://openseadragon.github.io/docs/

...so for them I prefer the `//` comments, which don't get turned into documentation on the site (whereas the `/**` comments do). Otherwise they're great... I just want them in the code, not the site.

**Comment by iangilman** [comment]
Never mind about the comment style... according to @avandecreme ([here](https://github.com/openseadragon/openseadragon/pull/1006/files/f0cb707ff238c0c9fcc7963524beff8797dc3e83..2e3f57401fa9eea094112fa0c317e26fdaaf2a42#r77874711)) `@private` doc comments are no longer shown on the public website... as you were!

**Comment by rdlester** [comment]
Yeah, my intent is to work on the bugs I filed. But, as I just commented, I no longer think the suggestion of #175 is worth it. I'll likely just be working on #173, which should be pretty straight-forward. Thought it'd be best to send a PR with style changes / comments prior to any actual changes. Didn't realize there were various PRs in progress affecting the same code.

Re: @avandecreme: I don't think I'll have time to entirely take over #1006, unfortunately. But, I could make my changes to your pending code; I could send PRs to your fork or something. Whatever you think works best.

**Comment by iangilman** [comment]
@rdlester #173 sounds good. Note that that area was touched upon with #1014, which took us partway there but caused #1020. #1025 is an attempted fix, but has its own issues. Hopefully you can help sort that out!

**Comment by iangilman** [comment]
@rdlester #1006 has landed, so you can now sort out the conflicts with this patch so it can land :)

**Comment by rdlester** [comment]
Conflicts have been resolved. I did it via a rebase, though, so I guess it's not showing up here explicitly? But, the travis-ci looks like it's re-running integration checks, so that marker should be up-to-date.

**Comment by iangilman** [comment]
Awesome... wonderful to have these comments in!

**Pull request merged**
