### PR TITLE
Added citation file

### PR DESCRIPTION
**Pull request by iangilman**
Someone has requested we add a citation file so they can cite the software. I know nothing about such things, but have now read up on them here:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

I made this file by going through the process here:

https://citation-file-format.github.io/cff-initializer-javascript/

Let me know if I should change anything!

One question in particular is who should be listed as the authors? I just went through and took everyone with over 100 commits listed at https://github.com/openseadragon/openseadragon/graphs/contributors. That's myself, @avandecreme,  @msalsbery, @thatcher, @pearcetm. Let me know if you don't want to be listed or if there are others that should be listed. As much as it would be nice to list all 170 contributors, that seems like it would be excessive! 😆

### CODE REVIEW

**Comment by iangilman** [comment]
It's tempting to add @aseemk, since he wrote the original version... What do you think, Aseem?

Presumably there are also big contributors during the time OpenSeadragon was on Codeplex, but I'm not sure how to know who they are.

**Comment by gaiborjosue** [comment]
Hello @iangilman, thank you so much for considering my suggestion on adding OSD citation feature! Lgtm :)

**Comment by aseemk** [comment]
> It's tempting to add @aseemk, since he wrote the original version... What do you think, Aseem?
> 
> Presumably there are also big contributors during the time OpenSeadragon was on Codeplex, but I'm not sure how to know who they are.

Thanks for thinking of me! 😊 Happy to be added, but only below you (and anyone else) @iangilman — my work def stood on your shoulders. 😃 Hope you're all well!!

**Comment by msalsbery** [comment]
😎👍

**Comment by avandecreme** [comment]
Hello @iangilman !

Thanks for adding me to the list!
And glad to see the project is still active! I unfortunately don't have the use for it in my current job but I am happy to randomly land on a web page which uses it :)

**Comment by pearcetm** [comment]
Looks good to me!

**Comment by iangilman** [comment]
Lovely... Thanks for chiming in, y'all! I've merged this now; the "Cite this repository" item now appears on the home page :)

**Pull request merged**
