### PR TITLE
Remove support for IE < 11 (#1863)

### PR DESCRIPTION
**Pull request by rmontroy**
Remove a  couple loose ends.

### CODE REVIEW

**Comment by msalsbery** [comment]
@rmontroy  Excellent, thank you!

**Review by msalsbery — APPROVED** [review]
Looks great to me! @iangilman ?

**Comment by rmontroy** [comment]
FYI, I installed/tested this branch in my project, and the `eval` use warning is gone now, which is a nice bonus.

Before:
```
$ npx snowpack build
[snowpack] ! building source files...
[snowpack] ✔ build complete [1.31s]
[snowpack] ! installing dependencies...
[snowpack] /Users/rob.montroy/git/virtual-slide-viewer/node_modules/openseadragon/build/openseadragon/openseadragon.js:2478:27 Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
[snowpack] ✔ install complete! [17.54s]
[snowpack] ! verifying build...
[snowpack] ✔ verification complete [0.01s]
[snowpack] ! writing build to disk...
[snowpack] ▶ Build Complete!
```

After:
```
$ npx snowpack build
[snowpack] ! building source files...
[snowpack] ✔ build complete [1.16s]
[snowpack] ! installing dependencies...
[snowpack] ✔ install complete! [16.92s]
[snowpack] ! verifying build...
[snowpack] ✔ verification complete [0.01s]
[snowpack] ! writing build to disk...
[snowpack] ▶ Build Complete!
```

**Review by iangilman — APPROVED** [review]
Looks great! We just need to add @rmontroy and this PR number to the appropriate change log item.

**Comment by msalsbery** [comment]
@rmontroy  One last thing: Can you please add an entry to changelog.txt?

**Comment by msalsbery** [comment]
@rmontroy  Merged, thank you again!

**Comment by iangilman** [comment]
Thank you both! I went ahead and consolidated the "IE < 11" changelog entries: 

https://github.com/openseadragon/openseadragon/commit/d4eaefbae1637477c2b9195157ba4a3f6c5209f7

**Pull request merged**
