### PR TITLE
Fix getTileAtPoint epsilon precision

### LINKED ISSUE #1362: Still second flickering image below some zoomed simple images
Hi,
looks like it's not fully fixed #1276 
Single Image 2000x3033 pixels

strange

```
var i = {
        type: 'image',
        url: value
      };
      if (!this.zoom) {
        this.zoom = OpenSeadragon({
          defaultZoomLevel: 0,
          element: this.seadragonViewer.nativeElement,
          showNavigator: true,
          navigatorPosition: 'BOTTOM_LEFT',
          prefixUrl: '/assets/openseadragen_imgs/',
          showZoomControl: false,
          minZoomLevel: 0,
          maxZoomLevel: 10,
          tileSources: i
        });
        $(this.zoom.element).find('.navigator').css('background-color', 'transparent');
        $(this.zoom.element).find('.navigator').css('border', 'none');
        $(this.zoom.element).find('.openseadragon-canvas').css('outline', 'none', "important");
        $(this.zoom.element).find('.displayregion').css('border-color', '#999');
      } else {
        this.zoom.open(i);
      }

```

### PR DESCRIPTION
**Pull request by avandecreme**
Fix #1362 

@iqmeta Could you test if this fix issue #1362 for you?

### CODE REVIEW

**Comment by iangilman** [comment]
Looks good to me (just looking at the code), but hopefully we can hear from @iqmeta.

**Comment by iqmeta** [comment]
Hi there,
okay did a grunt build of latest master. With the change of 1e-16 to 1e-15
But still double image/tile. My own hotfix is currently always have only 1 tile/image.
Maybe add an option if you know there is only one image?

image

**Comment by avandecreme** [comment]
@iqmeta I believe you did not pick this patch when testing.

This patch has not been merged to master, so to try it you should checkout that branch.
You can do so by running this commands in your git directory:
```
git checkout -b avandecreme-tile_at_point master
git pull git://github.com/avandecreme/openseadragon.git tile_at_point
```

On the screenshot you posted, the epsilon is the one used in `rectangle.js` instead of `tile-source.js`.

I created a 2000x3033 image to test this fix and it is working for me.

**Comment by iangilman** [comment]
@iqmeta Can you test again based on @avandecreme's instructions? 

If not, I guess we can go ahead and merge it...

**Pull request merged**
