### PR TITLE
fix Viewport flip logic for CanvasDrawer

### LINKED ISSUE #2477: Tiles in FOV hidden while zooming for certain Viewport & TiledImage rotation combinations
Looks like some logic that calculates whether tiles are in view is not correctly taking into account a rotation/flip value. 

[osd_rotation_bug-2024-02-21_10.18.38.webm](https://github.com/openseadragon/openseadragon/assets/22227739/19027821-9fdb-41ba-95cc-e9e31b5f475d)

[Here is a link to an example sandbox](https://codesandbox.io/p/sandbox/openseadragon-sandbox-forked-7hcfw7?file=%2Fsrc%2Findex.js%3A37%2C15&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsw0ywvg00072v6hngtlh49h%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsw0ywvg00032v6hd9h3xqfw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsw0ywvg00042v6h99qbxple%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsw0ywvg00062v6hbwdu5ral%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsw0ywvg00032v6hd9h3xqfw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsw0ywvg00022v6hauu15b2t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A37%252C%2522startColumn%2522%253A15%252C%2522endLineNumber%2522%253A37%252C%2522endColumn%2522%253A15%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clsw0ywvg00032v6hd9h3xqfw%2522%252C%2522activeTabId%2522%253A%2522clsw0ywvg00022v6hauu15b2t%2522%257D%252C%2522clsw0ywvg00062v6hbwdu5ral%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsw0ywvg00052v6h080o8ppl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsw0ywvg00062v6hbwdu5ral%2522%252C%2522activeTabId%2522%253A%2522clsw0ywvg00052v6h080o8ppl%2522%257D%252C%2522clsw0ywvg00042v6h99qbxple%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clsw0ywvg00042v6h99qbxple%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Exact repro steps:
- Add an image to OSD, then rotate, and flip the viewport:
```js
$.addTiledImage({
  tileSource: duomo,
  success: function () {
    $.viewport.setRotation(45, true);
    $.viewport.setFlip(true);
  },
});
```
- Add a second image that is rotated and flipped at the TiledImage level
```js
$.addTiledImage({
  composition: "source-over",
  index: 1,
  tileSource: duomo,
  success: function (evt) {
    evt.item.setRotation(45, true);
    evt.item.setFlip(true);
  },
});
```
- Zooming in/out should cause some tiles that are in the FOV to disappear

### PR DESCRIPTION
**Pull request by eug-L**
fixes #2477 

@pearcetm Thanks for your comments. The past 2 days have been hectic for me that's why I am only able to drop this now. Also been thinking about the best way to implement this fix.

If this method is suitable, would like to ask if I can include this flip logic in the new ```_setRotations``` function, since it was not included if ```sketchScale``` is true, not sure about the implications
[https://github.com/openseadragon/openseadragon/blob/9f7b18adb6877cf38962af28c9a939af61a7b72f/src/canvasdrawer.js#L333-L338](https://github.com/openseadragon/openseadragon/blob/9f7b18adb6877cf38962af28c9a939af61a7b72f/src/canvasdrawer.js#L333-L338)

I am also not sure how to setup testing since the clipping issue is a visual bug, would greatly appreciate guidance on this.

### CODE REVIEW

**Comment by pearcetm** [comment]
I tested out this change using the DrawerComparison demo page. You can do the same using "grunt dev" and going to http://localhost:8000/test/demo/drawercomparison.html 

Unfortunately, it seems that this fix doesn't solve the problem of dropped tiles in the CanvasDrawer when the TiledImage is rotated to a non-zero angle and the viewer is flipped. You'll also notice that the image pans the wrong direction too. Lots of stuff to track down here...

image

**Comment by pearcetm** [comment]
While looking into this, I ended up making a whole bunch of additional changes, so I opened a new PR - it seemed much easier than trying to describe all of it here! It would be great to have you test out the changes in https://github.com/openseadragon/openseadragon/pull/2511 to see if you find any further cases that need to be fixed.

Thank you for starting the process and inspiring me to dig further into the mess of the CanvasDrawer code!

**Comment by eug-L** [comment]
> I tested out this change using the DrawerComparison demo page. You can do the same using "grunt dev" and going to http://localhost:8000/test/demo/drawercomparison.html
> 
> Unfortunately, it seems that this fix doesn't solve the problem of dropped tiles in the CanvasDrawer when the TiledImage is rotated to a non-zero angle and the viewer is flipped. You'll also notice that the image pans the wrong direction too. Lots of stuff to track down here...

Thanks for suggesting the DrawerComparison page, I did not know about that!

Yes I observed the same problem as you did on the same settings. Thanks for testing this further! May I know what are dropped tiles?

We can proceed with your PR, I see you have included my changes, which means I can close this PR?

**Comment by pearcetm** [comment]
> May I know what are dropped tiles?

What I meant by "dropped tiles" is that parts of the image disappear inappropriately on zooming/panning, as shown in the screen capture videos in https://github.com/openseadragon/openseadragon/issues/2477. The same thing was happening in the drawer comparison demo - parts of the image get truncated because the tiles aren't drawn correctly.

> We can proceed with your PR, I see you have included my changes, which means I can close this PR?

Yes - since https://github.com/openseadragon/openseadragon/pull/2511 incorporates your change, it is safe to close this PR.

**Pull request closed without merging**
