### PR TITLE
fixed tabIndex to handle empty string

### LINKED ISSUE #769: page jumps when interacting with OSD
is it possible to disable this? can be seen on example pages

### PR DESCRIPTION
**Pull request by accraze**
chrome acts buggy and jumps when tabindex is not set to empty string.

fixes #769

### CODE REVIEW

**Comment by iangilman** [comment]
Thanks for tackling this! 

I think we still want to default to 0, but make it possible to set it to `""` if the developer wants. That would look something like this: 

```
this.canvas.tabIndex = (options.tabIndex === undefined ? 0 : options.tabIndex);
```

@msalsbery @avandecreme correct me if I'm wrong on defaulting to 0...we want that for keyboard support, right? Do you know exactly what it does for us?

**Comment by avandecreme** [comment]
I am not sure.
According to the [mozilla doc](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/tabIndex), shouldn't undefined, 0 and "" be equivalent?

@accraze how did you find out this was the cause of #769? Did you find any other documentation somewhere?

**Comment by accraze** [comment]
@avandecreme all info I got was in issue #769 ... the jump doesn't seem to be happening for me anymore in Chrome...

**Comment by iangilman** [comment]
Yeah, 0 and "" are definitely different, at least on Chrome. 

@accraze Can you update it so we still default to 0 but allow setting to ""?

**Comment by accraze** [comment]
sure no problem!

**Comment by iangilman** [comment]
@accraze Sorry, didn't see you had made the change! Looks great :)

**Pull request merged**
