### PR TITLE
update doc for Overlay

### PR DESCRIPTION
**Pull request by leesei**
~~replace `OpenSeadragon.Placement` with `OpenSeadragon.OverlayPlacement`~~
~~fix param name for `update()`~~

fix param for `update()`

 Changes to be committed:
	modified:   src/overlay.js

### CODE REVIEW

**Comment by leesei** [comment]
Oops, it seems we are trying to make `OverlayPlacement` obsolete?

**Comment by iangilman** [comment]
Yeah, we're moving towards `Placement`. That param name should be updated though.

**Comment by leesei** [comment]
I've updated my branch.

**Comment by iangilman** [comment]
@leesei Beautiful, thank you! (Sorry for the delay... I was out sick)

**Pull request merged**
