### PR TITLE
Removed duplicate event doc

### PR DESCRIPTION
**Pull request by iangilman**
...as reported here: 

https://twitter.com/richardttomkins/status/677715268018282496

cc @avandecreme

### CODE REVIEW

**Comment by avandecreme** [comment]
How come there isn't the same issue for 'open-failed'?

**Comment by iangilman** [comment]
Interesting! I have no idea… Maybe somehow JSDoc recognized them as being identical whereas it didn't with the "ready" event?

Perhaps we should clean out the second "open-failed" anyway, just for consistency? It seems like it's probably just as well to have just one doc per event.

**Comment by avandecreme** [comment]
Yes, I think we should remove the doc for open-failed as well.

**Comment by iangilman** [comment]
Cool; done: 

https://github.com/openseadragon/openseadragon/commit/5390cb96c70758ea2fb046f48815269ed95c1e78

**Pull request merged**
