### PR TITLE
docs: change `@return` -> `@returns`

### PR DESCRIPTION
**Pull request by shyamkumaryadav**
ref https://github.com/openseadragon/openseadragon/pull/1841

### CODE REVIEW

**Review by iangilman — COMMENTED** [review]
Beautiful, thank you! 

You mentioned that this closes #1841, and I'm seeing the change in Drawer from there, but not the change in IIIFTileSource (that I commented on in there). Would you be up for making that change as well? If not, we shouldn't close #1841 yet.

**Comment by shyamkumaryadav** [comment]
[r447836423](https://github.com/openseadragon/openseadragon/pull/1841/files#r447836423) isn't quite right either for me as [extra-functionality](https://iiif.io/api/image/3.0/#57-extra-functionality)

```diff
     * @param {Object} options
     * @param {Array|String} options.profile
     * @param {Number} options.version
-    * @param {Number} options.extraFeatures
+    * @param {String[]} options.extraFeatures

```

**Comment by iangilman** [comment]
Good point! Also, I'm seeing that a bunch of that has already been fixed, since #1841. But yeah, if you could fix `extraFeatures`, that would be great. Thank you for hunting down the spec!

**Review by iangilman — APPROVED** [review]
Lovely, thank you! I really appreciate how you are helping to keep things clean here :)

**Pull request merged**
