### PR TITLE
Removed createCallback function

### PR DESCRIPTION
**Pull request by akansjain**

### CODE REVIEW

**Comment by akansjain** [comment]
Hey @AndrewADev @iangilman  , Please review my PR.
Thanks.

**Review by iangilman — CHANGES_REQUESTED** [review]
Thank you for getting started on this! As discussed in https://github.com/openseadragon/openseadragon/issues/2365, we actually want to deprecate it instead of remove it. That means it needs to continue to function, but we need to add a `$.console.error` that explains that it's deprecated. 

In addition, remove the comment block above the function call and replace it with just `// deprecated`.

**Comment by akansjain** [comment]
@iangilman okay.

**Comment by akansjain** [comment]
Hey @iangilman , 

Can we use console.warn() instead of console.error()? I think this would make more sense.

For Example:-

function createCallback() {
  console.warn('The createCallback function is deprecated and will be removed in future versions. Please use alternativeFunction instead.');
  // Function implementation
}

**Comment by iangilman** [comment]
We generally use `console.error` for the deprecation messages, and I think that's a good idea, because what we're trying to do is get the developer to change their code now, so that when we remove the function in a future version, their code won't break. People would be more likely to ignore a `console.warn`.

**Comment by akansjain** [comment]
Hey @iangilman ,
Please review the commit.

**Review by iangilman — CHANGES_REQUESTED** [review]
Thank you. Just a few more details.

**Comment by akansjain** [comment]
Hey @iangilman , Please review the commit.

**Review by iangilman — APPROVED** [review]
Fantastic... Thank you for attending to all the details!

**Pull request merged**
