### PR TITLE
Adds collectionColumns as a configuration parameter

### PR DESCRIPTION
**Pull request by LarissaSmith**
Adds configuration parameter for collection mode to allow a horizontal layout that has a fixed number of columns or a vertical layout that has a fixed number of rows. This layout option was needed for an implementation that dynamically loads a large series of images.

### CODE REVIEW

**Comment by gechols** [comment]
@iangilman - this is a nice addition to the image collection feature. It helps things layout more like a book with a set # of columns for batches of thumbnails.

**Comment by iangilman** [comment]
Lovely, thank you! What would you think about adding a test for it in here? 

https://github.com/openseadragon/openseadragon/blob/master/test/modules/world.js#L185

**Comment by LarissaSmith** [comment]
Sure, I'll see what I can do.

**Comment by LarissaSmith** [comment]
@iangilman I added tests for collectionColumns.

**Comment by iangilman** [comment]
Awesome, thank you!

**Pull request merged**
