### PR TITLE
Changed full page sizing to 100% instead of compute fixed size (issue #2099)

### PR DESCRIPTION
**Pull request by TanukiSharp**
Fixes issue #2099 by setting viewer size to 100% instead of computed fixed size in full page mode.

### CODE REVIEW

**Review by iangilman — COMMENTED** [review]
Thank you for making this PR! One question: Might it be better to use `100vw` and `100vh`? Aren't there some circumstances where a height of 100% doesn't actually fill the page?

**Comment by TanukiSharp** [comment]
> Aren't there some circumstances where a height of 100% doesn't actually fill the page?

I don't see any, off the top of my head.

> Might it be better to use 100vw and 100vh?

In most situations, both will behave the same. The only difference would be, if for some reasons in the future the viewer is moved to a parent DOM element instead of being the top one, in 100% it will take the whole size of its new parent, whereas with vh/vw units, it will not be properly sized. But the purpose of "fullpage" mode is to take the full size of the whole page, so I don't see this would happen.

Whichever are fine with me, I would still go with the 100% unit, but maybe I'm missing something with the vh/vw units. Just out of curiosity, any particular reason why you would prefer this approach ?

**Comment by iangilman** [comment]
If there's not enough vertical content to fill the page, a 100% height div will only cover the area of the content. Here's an example: 

https://codepen.io/iangilman/pen/eYexZLE

Note that with `height: 100%` the teal rectangle is only as tall as the words on the page. With `height: 100vh` it fills the whole window. 

This is especially a concern with OSD, because the viewer doesn't have any inherent content height to it, so it could easily collapse to 0 in that scenario.

**Comment by TanukiSharp** [comment]
I think using the `vw`/`vh` unit is also fine.

Indeed I was focusing on `%` will take just enough and not too much, but I was not thinking about "it may take not enough space" part.

As long as in full page, the viewer becomes the first child of the body, the `vw`/`vh` units should be OK.

**Comment by iangilman** [comment]
Cool. Let's go with that then. Thank you for talking it through with me :)

**Comment by iangilman** [comment]
@TanukiSharp You'll make the change, right? Then I can merge it. No rush… Just making sure we're on the same page :-)

**Comment by TanukiSharp** [comment]
Sorry I should have mention that. Yes I will make the change, just a bit busy lately ^^

**Comment by TanukiSharp** [comment]
Update done, sorry for taking so long for such a small change ^^

**Review by iangilman — APPROVED** [review]
No worries... Thank you for getting to it!

**Pull request merged**
