### PR TITLE
Changed Console.log in SRC

### PR DESCRIPTION
**Pull request by Abhishek-90**
Change how internal console messages are written #1886

### CODE REVIEW

**Review by iangilman — CHANGES_REQUESTED** [review]
Looks great! I found one more: 

https://github.com/openseadragon/openseadragon/blob/c8f4934c8a5f33b15830d9a82e5443a48519db63/src/referencestrip.js#L270

I think that one should just be commented out. Can you make that change?

**Comment by Abhishek-90** [comment]
Hi @iangilman , I made the changes you requested in referencestrip.js line 270.

**Review by iangilman — APPROVED** [review]
Fantastic, thank you! I'll merge this after the upcoming release as we have a code freeze in place.

**Comment by iangilman** [comment]
Merging, now that 3.0 has been released!

**Pull request merged**
