### PR TITLE
Added new feature: mosaic layout

### PR DESCRIPTION
**Pull request by miguel-porto**
Hi,
I added a new layout `mosaic`, which packs a collection in a tidy mosaic.
See a demo here: [mosaic layout demo](http://www.flora-on.pt/mosaic/)
This was based on code from [here](http://blog.vjeux.com/wp-content/uploads/2012/05/google-layout.html).
Hope it's a good starting point for other neat layouts!
Best,

### CODE REVIEW

**Comment by iangilman** [comment]
Cool! Great idea. 

I'm a little conflicted about whether this should be part of the OpenSeadragon core... we already want to move collectionMode out into a plug-in (to encourage more flexibility and exploration), see #649. On the other hand, you've done a lovely job of integrating your code into OSD. Let's give it some thought... either way, we definitely need to make this available to the community!

BTW, thank you for documenting where the original code came from. Is there a license attached to it? Was it from a particular blog post?

**Comment by miguel-porto** [comment]
Thanks for the feedback! I still have to make a few changes in the code.
I have no strong opinion on the plugin vs. core thing. But yes, if more layout features are coming through, maybe making this a plugin will be the best approach.

Yes, the code was adapted from [this blog post](http://blog.vjeux.com/2014/image/google-plus-layout-find-best-breaks.html), but there is no license info at all, neither in the code, nor in the blog. I can contact the owner and see what he says.
best!

**Comment by iangilman** [comment]
Maybe just linking to the blog post is enough, though I imagine the author would love to hear about the code being used in a new place!

If you're up for trying it out as a plug-in, please do and let me know how it goes. We can add it to the growing list: http://openseadragon.github.io/#plugins

**Comment by Pin0** [comment]
I created a similar plugin: https://github.com/Pin0/openseadragon-justified-collection

**Comment by iangilman** [comment]
@Pin0 Beautiful! Can you add it to our plug-ins list?

https://github.com/openseadragon/site-build/blob/master/www/index.html#L148

@miguel-porto What do you think? Does @Pin0's plug-in accomplish what you wanted?

**Comment by Pin0** [comment]
@iangilman pull request made

**Comment by iangilman** [comment]
@Pin0 Excellent!

I'll wait to see if @miguel-porto has any followup comments, but I think maybe we can close this PR.

**Comment by miguel-porto** [comment]
I think it does pretty much the same thing, although slightly different input options; go ahead! If I have any ideas for improvement, I'll make upon @Pin0 's code!

**Comment by iangilman** [comment]
Awesome, sounds good. Thank you both!

**Pull request closed without merging**
