### PR TITLE
Provide coverage while loading tile

### PR DESCRIPTION
**Pull request by johnsusi**
This solves #1020 for me.

@iangilman and @CaptainCodeman might have some insight if this is the correct way to fix the issue.

Perhaps the tile opacity should be taken into account as well?

### CODE REVIEW

**Comment by CaptainCodeman** [comment]
The whole coverage / loaded / transparency is what I was focusing on but I was still trying to figure out exactly how all the pieces related - this looks exactly like the sort of issue / fix I imagined, I'll try it out to confirm.

**Comment by CaptainCodeman** [comment]
Works for me 👍

**Comment by iangilman** [comment]
The problem with this approach is that coverage is used both to determine which tiles should be loaded and also which tiles should be drawn. We don't want to end up in a situation where we've got a hole in the image because we're not drawing a tile that we have just because we're loading a higher resolution tile above it.

I can easily reproduce this issue with this patch: load up an image and zoom into it... you'll see holes appear as it loads higher resolution tiles.

So, we need to distinguish between those two kinds of coverage. One option would be to move the coverage data away from a pure true/false binary and make it true/false/'loading' or some such. Maybe there's something more elegant that could be done. 

Anyway, I think you're on the right track; it just needs some more refinement.

**Comment by iangilman** [comment]
Also, to note here (as discussed in Gitter): the current patch short circuits the "fully loaded" detection; that needs to keep track of whether there's anything loading, not just whether there's nothing yet to load.

Incidentally, #1014 made it so we keep drawing even while we're loading, which is great because it means we load more things in parallel, but a further refinement there could be to stop drawing during loading once we've run out of things to load.

**Comment by johnsusi** [comment]
Sorry for the late reply, been busy getting things out the door :)

Yes, the issue was more complex than I imagined. I am slowly learning the inner workings of openseadragon so this PR will need a lot more work. I'll leave it up for the discussion anyway.

About the `fully-loaded-changed` event. I tried it without this PR and it still failed. As far as I can tell it is fired when the last tile has been added to the work-queue and all tiles are in flight. 

Just for the sake of discussion:

`updateViewport` seems designed to be serial in nature. What if we redesigned it to just throw all visible and not loaded tiles onto the imageloader, not caring what tile is the best to load and then do the 'best' calculation in the imageloader instead when popping the queue.

fully-loaded and coverage could be moved aside (or even into a plugin hooking in to the 'tile-loaded' event. )

Obviously my use case for openseadragon is very limited so this might break other uses.

**Comment by iangilman** [comment]
@johnsusi See https://github.com/openseadragon/openseadragon/issues/1020#issuecomment-253274720 for my thoughts on a robust solution (that also incorporates other optimizations we've been considering). I think it's pretty similar to what you're suggesting in your most recent comment here.

Interesting that the `fully-loaded-change` event isn't working for you even without this patch. Just to be sure: I see in your comment you spelled it `fully-loaded-changed`, which is not correct; did you do that in your code as well?

**Comment by johnsusi** [comment]
@iangilman Looks good

Yes that was a typo. The event fired, (but to early)
I'm using a fork so there might be some problem there.

I'm gonna close this PR since it is no longer relevant.

**Comment by iangilman** [comment]
Sounds fair... thank you for your work on this!

**Pull request closed without merging**
