### PR TITLE
Collections

### PR DESCRIPTION
**Pull request by iangilman**
This pull request is for #386. This will take a while before it's ready to merge into master, but I'm creating it to provide visibility into the ongoing work. 

To Do Before Merging:

- [x] Specify width and/or height
- [x] Just one drawing surface and tileCache per viewer
- [x] Better concept of home
- [x] Fix broken unit tests
- [x] Figure out what to do about constraints
- [x] Navigator: should show full scene, not just one image
- [x] Navigator: viewport rectangle is wrong
- [x] Navigator: make sure it keeps the whole scene in view
- [x] Are we not getting the low-res tiles first? Drew is getting "tiley" load-ins
- [x] New API for viewer.open() and viewer creation that allows you to pass in a pile of tileSources along with positioning information
- [x] Update documentation
- [x] Make sure low-res tiles load for all of the images before any of them start loading hi-res tiles
- [x] How do we deal with wrapHorizontal and wrapVertical? 
- [x] Fix preserveViewport support
- [x] Test Viewport's fitVertically and fitHorizontally
- [x] Update changelog
- [x] Verify that rotation works with multi-image
- [x] Verify that overlays outside of the old 0,0 1,1 bounds work
- [x] Redo collection mode, sequences, etc. with the new API
- [x] Improved unit tests for the new functionality
- [x] Clean up code
- [x] Moving tiled images around

Stretch Goals:

- [x] Make sure viewport's "toImage" conversion functions work for the single-image case
- [x] TiledImage needs content coordinate conversions
- [x] tile-drawing event should specify which tiledImage
- [x] Moving tiled images around with springs

In A Future Patch:

- [ ] Opacity for tiledImages
- [x] Special grunt watch for min build mode
- [ ] Non-uniform scaling, where the width and height scales are different
- [x] Ability to start with an empty viewer and add images
- [x] addImage method (possibly the same as addLayer) 
- [x] Reconcile with overlays

### CODE REVIEW

**Comment by iangilman** [comment]
Just merged in #545 with a number of fixes:

* Erroneous asserts 
* Various unit test issues
* Navigator now updates when items move in the viewer
* Now possible to open with a single literal tilesource
* Pause button for the animation demo
* Fixed broken defaultZoomLevel and homeFillsViewer options

**Comment by iangilman** [comment]
Prepared a page on the multi-image coordinate system, for when this is released. Critiques welcome! https://github.com/openseadragon/site-build/pull/62

**Comment by avandecreme** [comment]
Great to have this.
I would add a demo giving the coordinates of the cursor in all 3 systems.
Something like the coordinate conversion section there: http://msalsbery.github.io/openseadragonimaginghelper/index.html

I am thinking this demo could maybe even let people add multiple images at different locations and size?

**Comment by iangilman** [comment]
@avandecreme good idea; I'll work on that.

**Comment by philipgiuliani** [comment]
Thanks for this fixes are looking very good :+1:
Docs are looking fine :)

**Comment by iangilman** [comment]
Ok folks, I think we're ready to merge this! Maybe as soon as tomorrow. :)

**Comment by msalsbery** [comment]
>I think we're ready to merge this! Maybe as soon as tomorrow

"I just want to tell you both good luck. We're all counting on you. "

**Comment by iangilman** [comment]
After 6 months, this branch is finally merged! Welcome to the world of multi-image, OpenSeadragon :)

**Comment by avandecreme** [comment]
:+1:

**Comment by aeschylus** [comment]
:+1:

Nice!

**Comment by philipgiuliani** [comment]
Cooool :) Nice!

**Pull request merged**
